### ISSUE TITLE
Does it support pruning for yoloV8？

### ISSUE THREAD

**Issue by gf-zhong** [blessonvar/DNNShifter#1]
Thank you for your excellent work. I have been working on YOLOV8 recently. Is it currently supported here?

**Comment by 123Bailey123** [comment]
Hi @gf-zhong, while this repository does not support YOLO models, it would be possible to re-implement DNNShifter since YOLO models contain convolutional layers. You would first need a highly sparse YOLO model, then prune with DNNShifter to get your desired results.
